package it.csi.stacore.stacoresrv.api.dto;

import java.util.Objects;
import java.util.ArrayList;

import java.io.Serializable;
import javax.validation.constraints.*;
public enum Contributo {
  MOTIVAZIONE_RIMBORSO,
  MOTIVAZIONE_STORNO_RIMBORSO,
  MOTIVAZIONE_CREAZIONE_CREDITO,
  MOTIVAZIONE_EROGAZIONE_CREDITO,
  MOTIVAZIONE_STORNO_CREDITO,
  MOTIVAZIONE_STORNO_PER_CHIUSURA_CREDITO,
  MOTIVAZIONE_EROGAZIONE_BONUS,
  MOTIVAZIONE_EROGAZIONE_CREDITO_POSITIVO_CALCOLO_COMPENSATO,
  MOTIVAZIONE_EROGAZIONE_CREDITO_NEGATIVO_CALCOLO_COMPENSATO,
  MOTIVAZIONE_EROGAZIONE_CREDITO_SANZIONI_INTERESSI_NON_DOVUTE,
  MOTIVAZIONE_EROGAZIONE_CREDITO_SANZIONI_NON_DOVUTE,
  CODICE_CONTRIBUTO_TASSA_NON_DOVUTA,
  CODICE_CONTRIBUTO_SANZIONI_ED_INTERESSI_NON_DOVUTI,
  CODICE_CONTRIBUTO_SU_IMPORTO_POSITIVO,
  CODICE_CONTRIBUTO_SU_IMPORTO_NEGATIVO,
  CODICE_CONTRIBUTO_SANZIONI_NON_DOVUTE;
}
