package it.csi.stacore.stacoresrv.api.dto;

import java.util.Objects;
import java.util.ArrayList;

import java.io.Serializable;
import javax.validation.constraints.*;
public enum TipoAgevolazione {
  SOSPENSIONE,
  ESENZIONE_PRESIDENTE_DELLA_REPUBBLICA,
  ESENZIONE_AUTOSCAFO_ADIBITO_A_PESCA,
  ESENZIONE_VEICOLO_HANDICAP,
  ESENZIONE_VEICOLO_STORICO,
  PERDITA_POSSESSO_PER_FURTO,
  PERDITA_POSSESSO_PROVVEDIMENTO_GIUDIZIARIO,
  AUTOBUS_ALISCAFO_SERVIZIO_POSTALE,
  AUTOCARRI_AUTOSCAFI_ESTINZIONE_INCENDI,
  TRASPORTO_PERSONE_PER_CURE_MEDICHE,
  SOSPENSIONE_PER_FALLIMENTO,
  SOSPENSIONE_EREDITA_GIACENTE,
  DEAMBULAZIONE_INVALIDI,
  TEMPORANEA_ESPORTAZIONE,
  AGENTI_DIPLOMATICI_CONSOLARI,
  ESENZIONI_PER_ECOINCENTIVI,
  VEICOLI_ONLUS,
  LR_22_2007_ART_11_INSTALLAZIONE_IMPIANTO_GAS,
  LR_23_2003_ART_5_LETT_A,
  LR_23_2003_ART_5_LETT_B_PROTEZIONE_CIVILE,
  LR_23_2003_ART_5_LETT_B_ESTINZIONE_INCENDI,
  LR_23_2003_ART_5_LETT_C,
  LR_23_2003_ART_5_LETT_D_AUTOBUS_PUBBLICO_DI_LINEA,
  LR_23_2003_ART_5_LETT_E_AMBULANZE_E_ASSIMILATI,
  LR_23_2003_ART_5_LETT_F_RIFIUTI,
  LR_23_2003_ART_5_LETT_G_ELETTRICI,
  LR_23_2003_ART_5_LETT_G_GPL_E_METANO,
  LR_23_2003_ART_5_LETT_H_ORGANIZZ_VOLUNTARIATO,
  LR_23_2003_ART_5_LETT_H_COOPERATIVE_SOCIALI,
  LR_23_2003_ART_5_LETT_H_IPAB,
  PATENTE_SPECIALE,
  B_POWER,
  GPL_METANO_ELETTRICI_ESCLUSIVI,
  IBRIDI,
  ESENZIONE_ESTINZIONE_INCENDI,
  ESENZIONE_AUTOBUS_IN_SERVIZIO_DI_LINEA,
  ESENZIONE_AMBULANZE,
  ESENZIONE_ATTI_AL_CARICO_SCARICO;
}
